Merge 'feature/us003-load-more-items'
walkdan/js-api-app pull request #2
Opened 2020-10-29 14:47 UTC by walkdan

2020-10-29 15:05 UTC, Vladyslav-Hrossu requested changes

2020-10-29 15:05 UTC, Vladyslav-Hrossu commented on src/scripts/modules/search-functions.js
> +  handleButtonSearchClick: function() {
ты можешь использовать стрелочные функции вместо колла/байнда

2020-10-29 15:05 UTC, Vladyslav-Hrossu commented on src/scripts/modules/search-functions.js
> +  return await new Promise( async (resolve, reject) => {
если используешь await то не нужно явно возвращать промис

2020-10-29 16:35 UTC, walkdan commented on src/scripts/modules/search-functions.js
> +  handleButtonSearchClick: function() {
я пробовал стрелочные функции... они берут this из внешнего окружения, т.е. тут thisом будет объект `listeners`. а мне нужно передавать объект `Search`

2020-10-29 16:38 UTC, walkdan commented on src/scripts/modules/search-functions.js
> +  return await new Promise( async (resolve, reject) => {
если явно не возвращать промис, то после выполнения функции автоматом будет возвращаться `fulfilled `промис, без `value`. а у меня функция возвращает данные после запроса

2020-10-30 10:25 UTC, walkdan commented on src/scripts/modules/search-functions.js
> +  return new Promise( async (resolve, reject) => {
убрал лишний await
https://github.com/walkdan/js-api-app/pull/2#discussion_r514331330

2020-10-30 10:28 UTC, walkdan commented on src/scripts/modules/search.js
> +    searchData = await searchFunctions.getSearchData(url);
т.к. здесь дожидаюсь резолва
https://github.com/walkdan/js-api-app/pull/2#discussion_r514999169

2020-10-30 13:07 UTC, Vladyslav-Hrossu requested changes

2020-10-30 13:07 UTC, Vladyslav-Hrossu commented on src/scripts/modules/search-functions.js
> +  return new Promise( async (resolve, reject) => {
Утебя асинк и так возвращает промис, зачем тебе еще конструктор промиса

2020-10-30 13:20 UTC, merged